# Development Docker Compose Override
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  # Development overrides for MCP Manager
  mcp-manager:
    build:
      target: builder  # Use builder stage for development
    environment:
      - NODE_ENV=development
      - DEBUG_ENABLED=true
      - HOT_RELOAD_ENABLED=true
      - LOG_LEVEL=debug
      - API_DOCS_ENABLED=true
    volumes:
      # Mount source code for hot reload
      - ../src:/app/src:ro
      - ../frontend:/app/frontend:ro
      - ../config:/app/config:rw
      - ../package.json:/app/package.json:ro
    command: ["npm", "run", "dev"]
    ports:
      - "8080:8080"
      - "5173:5173"  # Vite dev server
    networks:
      - mcp_network

  # Development Redis with less strict settings
  redis:
    command: [
      "redis-server",
      "--appendonly", "no",
      "--save", "",
      "--maxmemory", "128mb",
      "--maxmemory-policy", "allkeys-lru"
    ]
    ports:
      - "6379:6379"

  # Open WebUI development settings
  open-webui:
    environment:
      - WEBUI_SECRET_KEY=dev-secret-key
      - LOG_LEVEL=debug
    volumes:
      - ../frontend/dist:/app/frontend:ro

  # Ollama with development models
  ollama:
    environment:
      - OLLAMA_DEBUG=1
      - OLLAMA_VERBOSE=1

  # Development tools container
  dev-tools:
    image: node:18-alpine
    container_name: mcp-dev-tools
    working_dir: /app
    volumes:
      - ..:/app:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: ["tail", "-f", "/dev/null"]
    networks:
      - mcp_network
    profiles:
      - tools

# Development-specific volumes
volumes:
  mcp_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../config