#!/bin/bash
# BoarderframeOS MCP Server Startup Script
# Generated by health check

echo "Starting offline MCP servers..."


# Start Registry Server
echo "Starting Registry Server on port 8009..."
python mcp/registry_server.py --port 8009 &
sleep 2

echo "All servers started. Check mcp_servers.log for details."
