#!/usr/bin/env python3
"""
Update the departments tab to use the metrics layer
"""

import re

def update_departments_to_metrics():
    """Update departments display to use metrics layer"""
    print("🔧 Updating Departments Tab to use Metrics Layer")
    print("=" * 60)
    
    file_path = "/Users/cosburn/BoarderframeOS/corporate_headquarters.py"
    
    with open(file_path, 'r') as f:
        content = f.read()
    
    # Find where department cards are being generated by division
    # Look for the _generate_divisions_html method
    divisions_method_start = content.find("def _generate_divisions_html(self):")
    
    if divisions_method_start > 0:
        print("✅ Found _generate_divisions_html method")
        
        # Find the end of the method (next method definition)
        next_method = content.find("\n    def ", divisions_method_start + 10)
        method_content = content[divisions_method_start:next_method]
        
        # Check if we need to update it
        if "self.metrics_layer.get_department_cards_html()" not in method_content:
            print("📝 Updating to use metrics layer...")
            
            # Find where we return the division HTML
            return_start = method_content.find("return '''")
            if return_start > 0:
                # Insert a check for metrics layer
                pre_return = method_content[:return_start]
                post_return = method_content[return_start:]
                
                new_check = """        # If metrics layer is available, use it for department cards
        if hasattr(self, 'metrics_layer') and self.metrics_layer:
            return self.metrics_layer.get_department_cards_html()
        
        # Otherwise, use the existing implementation
        """
                
                new_method = pre_return + new_check + post_return
                content = content[:divisions_method_start] + new_method + content[next_method:]
                
                print("✅ Added metrics layer check to divisions HTML")
    
    # Also update the departments tab container to handle metrics layer output
    dept_tab_pattern = r'<div id="departments" class="tab-content">[\s\S]*?<!-- Department Overview Card -->'
    
    dept_replacement = '''<div id="departments" class="tab-content">
            <!-- Department Overview Card -->'''
    
    # Find where departments content is placed
    dept_content_pattern = r'(<div style="grid-column: span 12;">)([\s\S]*?)({self\._generate_divisions_html\(\)})([\s\S]*?)(</div>)'
    
    dept_content_replacement = r'''\1\2
                <!-- Use metrics layer if available, otherwise use division view -->
                {self.metrics_layer.get_department_cards_html() if hasattr(self, 'metrics_layer') and self.metrics_layer else self._generate_divisions_html()}
            \5'''
    
    content = re.sub(dept_content_pattern, dept_content_replacement, content, flags=re.DOTALL)
    
    # Write the updated content
    with open(file_path, 'w') as f:
        f.write(content)
    
    print("\n✅ Departments tab updated!")
    print("\n📊 Changes made:")
    print("   - Added metrics layer check in _generate_divisions_html")
    print("   - Updated departments tab to use metrics layer cards")
    print("   - Fallback to existing implementation if metrics unavailable")
    
    print("\n🚀 The departments tab will now use the metrics layer!")


if __name__ == "__main__":
    update_departments_to_metrics()