config:
  description: A simple test agent
  type: test
  version: 0.1.0
created: '2025-05-23T03:43:51.906546'
generation: 1
mutations: []
name: test-agent
parent: null
version: 20250523_034351_8e0f9165
